### ISSUE TITLE
[Bug] bokeh 1.4.0 is incompatible with python 3.12

### ISSUE THREAD

**Issue by rhdunn** [idiap/coqui-ai-TTS#218]
### Describe the bug

Running `pip install -e .[notebooks]` on Ubuntu 24.10 fails when installing bokeh.

### To Reproduce

`pip install -e .[notebooks]`

### Expected behavior

Installs dependencies and works.

### Logs

```shell
Collecting bokeh==1.4.0 (from coqui-tts==0.25.1)
  Using cached bokeh-1.4.0.tar.gz (32.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [34 lines of output]
      /tmp/pip-install-zbf1lejd/bokeh_2612f9730bdd4528a8bee049e4cb0044/versioneer.py:417: SyntaxWarning: invalid escape sequence '\s'
        LONG_VERSION_PY['git'] = '''
      Traceback (most recent call last):
        File "/mnt/data/ai/tts/coqui-ai/coqui-tts.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/mnt/data/ai/tts/coqui-ai/coqui-tts.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/mnt/data/ai/tts/coqui-ai/coqui-tts.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-cvgts4ot/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-cvgts4ot/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-cvgts4ot/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-cvgts4ot/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 124, in <module>
        File "/tmp/pip-install-zbf1lejd/bokeh_2612f9730bdd4528a8bee049e4cb0044/_setup_support.py", line 240, in get_version
          return versioneer.get_version()
                 ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-zbf1lejd/bokeh_2612f9730bdd4528a8bee049e4cb0044/versioneer.py", line 1487, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "/tmp/pip-install-zbf1lejd/bokeh_2612f9730bdd4528a8bee049e4cb0044/versioneer.py", line 1419, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-zbf1lejd/bokeh_2612f9730bdd4528a8bee049e4cb0044/versioneer.py", line 341, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
```
```


### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "NVIDIA GeForce RTX 3070 Laptop GPU"
        ],
        "available": true,
        "version": "12.1"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.5.1+cu121",
        "TTS": "0.25.1",
        "numpy": "1.26.4"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.12.7",
        "version": "#14-Ubuntu SMP PREEMPT_DYNAMIC Sat Nov 30 23:51:51 UTC 2024"
    }
}
```

### Additional context

I've found https://stackoverflow.com/questions/78577517/bokeh-newer-versions-does-not-work-with-pytrendline-while-older-versions-are-un which states that this is due to `versioneer` being incompatible with Python 3.11 and later. Newer versions of bokeh removed that dependency to resolve this issue.

I don't know what code changes are needed to support newer versions of bokeh.

**Comment by eginhard** [comment]
Yes, bokeh is pinned to a really old version, not sure why. Maybe I'll just remove it from the `notebooks` extra and add a `! pip install bokeh` in the one notebook where it's used. In the meantime, you can do `pip install coqui-tts pandas umap-learn` to just install the other packages from the `notebooks` extra.
