### ISSUE TITLE
[Bug] HIP/AMD not woking >= 0.24.3

### ISSUE THREAD

**Issue by jlucaso1** [idiap/coqui-ai-TTS#220]
### Describe the bug

0.24.2 works fine in my amd GPU, but newer version don't

### To Reproduce

Run any tts command

### Expected behavior

Don't throw error

### Logs

```shell
Traceback (most recent call last):
  File "/run/media/jlucaso/secondary/projects/speecher/apps/tts/.venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/jlucaso/secondary/projects/speecher/apps/tts/.venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/jlucaso/secondary/projects/speecher/apps/tts/.venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/jlucaso/secondary/projects/speecher/apps/tts/.venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/jlucaso/secondary/projects/speecher/apps/tts/server.py", line 76, in synthesize
    wav = tts.tts(text=text, speaker_wav=save_path, language=language)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/jlucaso/secondary/projects/speecher/apps/tts/.venv/lib/python3.12/site-packages/TTS/api.py", line 276, in tts
    wav = self.synthesizer.tts(
          ^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/jlucaso/secondary/projects/speecher/apps/tts/.venv/lib/python3.12/site-packages/TTS/utils/synthesizer.py", line 386, in tts
    outputs = self.tts_model.synthesize(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/jlucaso/secondary/projects/speecher/apps/tts/.venv/lib/python3.12/site-packages/TTS/tts/models/xtts.py", line 426, in synthesize
    return self.full_inference(text, speaker_wav, language, **settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/jlucaso/secondary/projects/speecher/apps/tts/.venv/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/jlucaso/secondary/projects/speecher/apps/tts/.venv/lib/python3.12/site-packages/TTS/tts/models/xtts.py", line 487, in full_inference
    (gpt_cond_latent, speaker_embedding) = self.get_conditioning_latents(
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/jlucaso/secondary/projects/speecher/apps/tts/.venv/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/jlucaso/secondary/projects/speecher/apps/tts/.venv/lib/python3.12/site-packages/TTS/tts/models/xtts.py", line 370, in get_conditioning_latents
    speaker_embedding = self.get_speaker_embedding(audio, load_sr)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/jlucaso/secondary/projects/speecher/apps/tts/.venv/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/jlucaso/secondary/projects/speecher/apps/tts/.venv/lib/python3.12/site-packages/TTS/tts/models/xtts.py", line 323, in get_speaker_embedding
    audio_16k = torchaudio.functional.resample(audio, sr, 16000)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/jlucaso/secondary/projects/speecher/apps/tts/.venv/lib/python3.12/site-packages/torchaudio/functional/functional.py", line 1519, in resample
    kernel, width = _get_sinc_resample_kernel(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/jlucaso/secondary/projects/speecher/apps/tts/.venv/lib/python3.12/site-packages/torchaudio/functional/functional.py", line 1417, in _get_sinc_resample_kernel
    idx = torch.arange(-width, width + orig_freq, dtype=idx_dtype, device=device)[None, None] / orig_freq
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: HIP error: invalid device function
HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing AMD_SERIALIZE_KERNEL=3
Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.
```
```


### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "AMD Radeon RX 6600"
        ],
        "available": true,
        "version": null
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.5.1+rocm6.2",
        "TTS": "0.25.1",
        "numpy": "1.26.4"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "",
        "python": "3.12.7",
        "version": "#1 SMP PREEMPT_DYNAMIC Mon, 09 Dec 2024 14:31:57 +0000"
    }
}
```

**Comment by eginhard** [comment]
The issue seems to be with Pytorch, not Coqui, probably https://github.com/pytorch/pytorch/issues/132570. Maybe a different Pytorch version works?
