### ISSUE TITLE
[Bug] Python 3.12 is not supported

### ISSUE THREAD

**Issue by yodatak** [idiap/coqui-ai-TTS#6]
### Describe the bug

Hi thanks a lot to make a fork and maintain this 
in Fedora 39 ( next will be python 3.13 i think) with 
python --version                                                                                                                                                                                         
Python 3.12.2

i canniot install because of 
pip install coqui-tts                                                                                                                                                                                     ⬢ [fedora-toolbox:39] 
Defaulting to user installation because normal site-packages is not writeable
ERROR: Ignored the following versions that require a different python version: 0.22.1 Requires-Python <3.12,>=3.9.0
ERROR: Could not find a version that satisfies the requirement coqui-tts (from versions: none)
ERROR: No matching distribution found for coqui-tt

### To Reproduce

You can create or run a docker image of fedora 39 with https://github.com/containers/toolbox and try to install coqui-tts

### Environment

```shell
 02:29  python3 collect_env_info.py                                                                                                                                                                               ⬢ [fedora-toolbox:39] 
Traceback (most recent call last):
  File "/var/home/yodatak/Projets/public/TTS/TTS/collect_env_info.py", line 7, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
```

**Comment by yodatak** [comment]
and with a venv and pip install -r requirement.txt

  Downloading matplotlib-3.8.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.8 kB)
ERROR: Ignored the following versions that require a different python version: 0.0.10 Requires-Python >=3.6.0, <3.10; 0.0.11 Requires-Python >=3.6.0, <3.11; 0.0.12 Requires-Python >=3.6.0, <3.11; 0.0.13 Requires-Python >=3.6.0, <3.11; 0.0.14 Requires-Python >=3.6.0, <3.11; 0.0.15 Requires-Python >=3.6.0, <3.11; 0.0.16 Requires-Python >=3.6.0, <3.11; 0.0.17 Requires-Python >=3.6.0, <3.11; 0.0.18 Requires-Python >=3.6.0, <3.11; 0.0.19 Requires-Python >=3.6.0, <3.11; 0.0.20 Requires-Python >=3.6.0, <3.11; 0.0.21 Requires-Python >=3.6.0, <3.11; 0.0.22 Requires-Python >=3.6.0, <3.11; 0.0.23 Requires-Python >=3.6.0, <3.11; 0.0.24 Requires-Python >=3.6.0, <3.11; 0.0.25 Requires-Python >=3.6.0, <3.11; 0.0.26 Requires-Python >=3.6.0, <3.11; 0.0.27 Requires-Python >=3.6.0, <3.12; 0.0.28 Requires-Python >=3.6.0, <3.12; 0.0.29 Requires-Python >=3.6.0, <3.12; 0.0.30 Requires-Python >=3.6.0, <3.12; 0.0.31 Requires-Python >=3.6.0, <3.12; 0.0.32 Requires-Python >=3.6.0, <3.12; 0.0.33 Requires-Python >=3.6.0, <3.12; 0.0.34 Requires-Python >=3.6.0, <3.12; 0.0.35 Requires-Python >=3.6.0, <3.12; 0.0.36 Requires-Python >=3.6.0, <3.12; 0.0.5 Requires-Python >=3.6.0, <3.10; 0.0.6 Requires-Python >=3.6.0, <3.10; 0.0.7 Requires-Python >=3.6.0, <3.10; 0.0.8 Requires-Python >=3.6.0, <3.10; 0.0.9 Requires-Python >=3.6.0, <3.10; 1.10.0 Requires-Python <3.12,>=3.8; 1.10.0rc1 Requires-Python <3.12,>=3.8; 1.10.0rc2 Requires-Python <3.12,>=3.8; 1.10.1 Requires-Python <3.12,>=3.8; 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11; 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10; 1.7.2 Requires-Python >=3.7,<3.11; 1.7.3 Requires-Python >=3.7,<3.11; 1.8.0 Requires-Python >=3.8,<3.11; 1.8.0rc1 Requires-Python >=3.8,<3.11; 1.8.0rc2 Requires-Python >=3.8,<3.11; 1.8.0rc3 Requires-Python >=3.8,<3.11; 1.8.0rc4 Requires-Python >=3.8,<3.11; 1.8.1 Requires-Python >=3.8,<3.11; 1.9.0 Requires-Python >=3.8,<3.12; 1.9.0rc1 Requires-Python >=3.8,<3.12; 1.9.0rc2 Requires-Python >=3.8,<3.12; 1.9.0rc3 Requires-Python >=3.8,<3.12; 1.9.1 Requires-Python >=3.8,<3.12
ERROR: Could not find a version that satisfies the requirement trainer>=0.0.36 (from versions: none)
ERROR: No matching distribution found for trainer>=0.0.36

**Comment by yodatak** [comment]
pip install -e .[all]                                                                                                                                                                                     ⬢ [fedora-toolbox:39] 
Obtaining file:///var/home/yodatak/Projets/public/coqui-ai-TTS
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Traceback (most recent call last):
        File "/var/home/yodatak/Projets/public/coqui-ai-TTS/coqui/lib64/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/var/home/yodatak/Projets/public/coqui-ai-TTS/coqui/lib64/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/var/home/yodatak/Projets/public/coqui-ai-TTS/coqui/lib64/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 132, in get_requires_for_build_editable
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-fxvfz1tn/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 448, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-fxvfz1tn/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-fxvfz1tn/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-fxvfz1tn/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-fxvfz1tn/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 36, in <module>
      RuntimeError: TTS requires python >= 3.9 and < 3.12 but your Python version is 3.12.2 (main, Feb 21 2024, 00:00:00) [GCC 13.2.1 20231205 (Red Hat 13.2.1-6)]
      [end of output]

**Comment by eginhard** [comment]
Thanks @yodatak for opening this issue. Yes, Python 3.12 is not supported yet. 

@theoparis would you still be interested in making a PR for this? Otherwise I will take care of it soon.

**Comment by eginhard** [comment]
Python 3.12 is now supported in version 0.23.1

**Comment by yodatak** [comment]
Thanks it works now but i got some issues ( not sure if its linked )

Traceback (most recent call last):
  File "/var/home/yodatak/.local/bin/tts", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/var/home/yodatak/.local/lib/python3.12/site-packages/TTS/bin/synthesize.py", line 345, in main
    from TTS.api import TTS
  File "/var/home/yodatak/.local/lib/python3.12/site-packages/TTS/api.py", line 11, in <module>
    from TTS.utils.synthesizer import Synthesizer
  File "/var/home/yodatak/.local/lib/python3.12/site-packages/TTS/utils/synthesizer.py", line 12, in <module>
    from TTS.tts.configs.vits_config import VitsConfig
  File "/var/home/yodatak/.local/lib/python3.12/site-packages/TTS/tts/configs/vits_config.py", line 5, in <module>
    from TTS.tts.models.vits import VitsArgs, VitsAudioConfig
  File "/var/home/yodatak/.local/lib/python3.12/site-packages/TTS/tts/models/vits.py", line 28, in <module>
    from TTS.tts.models.base_tts import BaseTTS
  File "/var/home/yodatak/.local/lib/python3.12/site-packages/TTS/tts/models/base_tts.py", line 20, in <module>
    from TTS.tts.utils.visual import plot_alignment, plot_spectrogram
  File "/var/home/yodatak/.local/lib/python3.12/site-packages/TTS/tts/utils/visual.py", line 2, in <module>
    import matplotlib
  File "/var/home/yodatak/.local/lib/python3.12/site-packages/matplotlib/__init__.py", line 161, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "/var/home/yodatak/.local/lib/python3.12/site-packages/matplotlib/rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "/var/home/yodatak/.local/lib/python3.12/site-packages/matplotlib/colors.py", line 52, in <module>
    from PIL import Image
  File "/var/home/yodatak/.local/lib/python3.12/site-packages/PIL/Image.py", line 103, in <module>
    from . import _imaging as core
ImportError: libjpeg.so.62: cannot open shared object file: No such file or directory


i install from fedora then dnf install python3-pillow (  and the depencies libjpeg-turbo openjpeg2 ...) and now it works huge thanks !

**Comment by eginhard** [comment]
Thanks for the feedback! Those look like issues with system dependencies that are outside the control of the package - on the Python side anything necessary should be included. But it sounds like you got it to work.
