### ISSUE TITLE
[Bug] logging error

### ISSUE THREAD

**Issue by pablodz** [idiap/coqui-ai-TTS#69]
### Describe the bug

This appears on the log while doing synth

https://github.com/idiap/coqui-ai-TTS/blob/dev/TTS/utils/synthesizer.py#L506-L507

### To Reproduce

I'm doing 

```python
wavs = synthesizer.tts(text, speaker_name=speaker_idx)
```

with MLS_20 as speaker_name and text of "<Imil sseeiss millones ciento sseesseentaiocho mil sseeteecientos ochentaitrés>"

### Expected behavior

Synth without errors

### Logs

```shell
Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.local/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.local/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.local/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/main.py", line 149, in tts
    wavs = synthesizer.tts(text, speaker_name=speaker_idx)
  File "/root/.local/lib/python3.10/site-packages/TTS/utils/synthesizer.py", line 507, in tts
    logger.info("Real-time factor: %.3f", process_time / audio_time)
ZeroDivisionError: float division by zero
```

### Environment

```shell
{
    "CUDA": {
        "GPU": [],
        "available": false,
        "version": "12.1"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.3.1+cu121",
        "TTS": "0.24.1",
        "numpy": "1.25.2"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            ""
        ],
        "processor": "x86_64",
        "python": "3.10.11",
        "version": "#1 SMP Tue Jun 18 14:00:06 UTC 2024"
    }
}
```

**Comment by eginhard** [comment]
@pablodz Which TTS model are you using here?

**Comment by pablodz** [comment]
I did a workaround to fix the input text first, looks like is something wrong with special characters, but should not be handled by model, so I'm closing the issue
