### ISSUE TITLE
[Bug] tts-server unable to start with xtts_v2 model

### ISSUE THREAD

**Issue by rohitkrishna094** [idiap/coqui-ai-TTS#99]
### Describe the bug

When I run `tts-server --model_name tts_models/multilingual/multi-dataset/xtts_v2`, I am getting the below error:

```
tts_models/multilingual/multi-dataset/xtts_v2 is already downloaded.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "<my-path>\my-env\Scripts\tts-server.exe\__main__.py", line 4, in <module>
  File "<my-path>\my-env\Lib\site-packages\TTS\server\server.py", line 110, in <module>
    synthesizer = Synthesizer(
                  ^^^^^^^^^^^^
  File "<my-path>\my-env\Lib\site-packages\TTS\utils\synthesizer.py", line 96, in __init__
    self._load_tts(tts_checkpoint, tts_config_path, use_cuda)
  File "<my-path>\my-env\Lib\site-packages\TTS\utils\synthesizer.py", line 186, in _load_tts
    self.tts_config = load_config(tts_config_path)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<my-path>\my-env\Lib\site-packages\TTS\config\__init__.py", line 85, in load_config
    ext = os.path.splitext(config_path)[1]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 258, in splitext
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

### To Reproduce

Just run `tts-server --model_name tts_models/multilingual/multi-dataset/xtts_v2`

### Expected behavior

To start the tts-server without any errors

### Logs

```shell
tts_models/multilingual/multi-dataset/xtts_v2 is already downloaded.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "<my-path>\my-env\Scripts\tts-server.exe\__main__.py", line 4, in <module>
  File "<my-path>\my-env\Lib\site-packages\TTS\server\server.py", line 110, in <module>
    synthesizer = Synthesizer(
                  ^^^^^^^^^^^^
  File "<my-path>\my-env\Lib\site-packages\TTS\utils\synthesizer.py", line 96, in __init__
    self._load_tts(tts_checkpoint, tts_config_path, use_cuda)
  File "<my-path>\my-env\Lib\site-packages\TTS\utils\synthesizer.py", line 186, in _load_tts
    self.tts_config = load_config(tts_config_path)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<my-path>\my-env\Lib\site-packages\TTS\config\__init__.py", line 85, in load_config
    ext = os.path.splitext(config_path)[1]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 258, in splitext
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

### Environment

```shell
{
    "CUDA": {
        "GPU": [],
        "available": false,
        "version": null
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.4.1+cpu",
        "TTS": "0.24.2",
        "numpy": "1.26.4"
    },
    "System": {
        "OS": "Windows",
        "architecture": [
            "64bit",
            "WindowsPE"
        ],
        "processor": "Intel64 Family 6 Model 94 Stepping 3, GenuineIntel",
        "python": "3.12.4",
        "version": "10.0.19045"
    }
}
```

**Comment by eginhard** [comment]
Yes, the server currently only supports a limited number of models. I'd merge a PR adding support for XTTS. Some previous discussion and workarounds are here: https://github.com/coqui-ai/TTS/issues/3140

**Comment by eginhard** [comment]
We now support all Coqui TTS models in the server. Specifying a `speaker_wav` file is not possible yet, this is tracked in #254.
